DISCORD_TOKEN="the discord bot token"
SPOTIFY_USERNAME="rolandpose70@gmail.com"
SPOTIFY_PASSWORD="1"
DISCORD_USER_ID="roland"
SPOTIFY_BOT_AUTOPLAY=true
SPOTIFY_DEVICE_NAME="custom device name in spotify, optional"
